MVC/FFMP/FFMP/Controllers/ObjectToCheckController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FFMP.Data;
using Microsoft.AspNetCore.Identity;
using FFMP.Models;
using FFMP.BlobStorageServices;
using System.Collections;

namespace FFMP.Controllers
{
    public class ObjectToCheckController : Controller
    {
        private readonly project_3Context _context;
        private readonly IHttpContextAccessor _cntxt;
        private readonly IBlobStorageService _blobStorage;

        public ObjectToCheckController(project_3Context context, IHttpContextAccessor cntxt, IBlobStorageService blobStorage)
        {
            _context = context;
            _cntxt = cntxt;
            _blobStorage = blobStorage;
        }

        // GET: ObjectToCheck
        public async Task<IActionResult> Index()
        {
            if (!UsersController.UserAuthenticated(_cntxt))
                return RedirectToAction("Login", "Users");

            var project_3Context = _context.ObjectToChecks.Include(o => o.TargetGroup).Include(o => o.UserLoginNavigation);
            return View(await project_3Context.ToListAsync());
        }

        // GET: ObjectToCheck/Details/5
        public async Task<IActionResult> Details(uint? id)
        {
            if (id == null || _context.ObjectToChecks == null)
            {
                return NotFound();
            }
            var objectToCheck = await _context.ObjectToChecks
                .Include(o => o.TargetGroup)
                .Include(o => o.UserLoginNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (objectToCheck == null)
            {
                return NotFound();
            }

            return View(objectToCheck);
        }
        // POST: InspectionCreate
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateInspection([Bind("Id,UserLogin,ObjectId,/*Timestamp*/,Reason,Observations,ChangeOfState,Inspectioncol")] Inspection inspection, List<IFormFile> files)
        {

            var objectInspected = await _context.ObjectToChecks.FindAsync(inspection.ObjectId);

            List<string> fileNames = new List<string>();
            foreach (IFormFile file in files)
            {
                if (file.Length < 5097152)
                {
                    await _blobStorage.UploadBlobFileAsync(file);
                    fileNames.Add(file.FileName);
                }
            }
            string combinedString = string.Join(",", fileNames);
            var insp = new Inspection();
            insp.UserLogin = _cntxt!.HttpContext.Session.GetString("userlogin");
            insp.ObjectId = inspection.ObjectId;
            insp.Reason = inspection.Reason;
            insp.Observations = inspection.Observations;
            insp.ChangeOfState = inspection.ChangeOfState;

            insp.Inspectioncol = combinedString;


            if(insp.ChangeOfState != objectInspected!.State)
            {
                objectInspected.State = inspection.ChangeOfState;
                _context.Update(objectInspected);
                await _context.SaveChangesAsync();
            }
                

            if (insp != null)
            {

                _context.Add(insp);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(InspectionController.ObjectsInspections), "Inspection", new {id = insp.ObjectId});
            }

            return RedirectToAction(nameof(Index));
        }

        //GET: ObjectToCheck/Create
        public IActionResult Create()
        {
            ViewData["TargetGroupId"] = new SelectList(_context.TargetGroups, "Id", "Id");
            ViewData["UserLogin"] = new SelectList(_context.Users, "Login", "Login");
            return PartialView("_CreateObjectPartialView");
        }

        // POST: ObjectToCheck/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UserLogin,TargetGroupId,Name,Description,Location,Type,Model")] ObjectToCheck objectToCheck)
        {
            var obj = new ObjectToCheck();
            obj.UserLogin = _cntxt!.HttpContext.Session.GetString("userlogin");
            obj.TargetGroupId = objectToCheck.TargetGroupId;
            obj.Name = objectToCheck.Name;
            obj.Description = objectToCheck.Description;
            obj.Location = objectToCheck.Location;
            obj.Type = objectToCheck.Type;
            obj.Model = objectToCheck.Model;

            if (obj != null)
            {
                _context.Add(obj);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            //ViewData["UserLogin"] = new SelectList(_context.Users, "Login", "Login", objectToCheck.UserLogin);
            //ViewData["TargetGroupId"] = new SelectList(_context.TargetGroups, "Id", "Id", objectToCheck.TargetGroupId);
            return RedirectToAction(nameof(Index));
        }

        // GET: ObjectToCheck/Edit/5
        public async Task<IActionResult> Edit(uint? id)
        {
            if (id == null || _context.ObjectToChecks == null)
            {
                return NotFound();
            }

            var objectToCheck = await _context.ObjectToChecks.FindAsync(id);
            if (objectToCheck == null)
            {
                return NotFound();
            }
            ViewData["TargetGroupId"] = new SelectList(_context.TargetGroups, "Id", "Id", objectToCheck.TargetGroupId);
            ViewData["UserLogin"] = new SelectList(_context.Users, "Login", "Login", objectToCheck.UserLogin);
            return PartialView("_EditPartialView", objectToCheck);
        }

        // POST: ObjectToCheck/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(uint id, [Bind("Id,UserLogin,TargetGroupId,Name,Description,Location,Type,Model,State")] ObjectToCheck objectToCheck)
        {
            var otc = await _context.ObjectToChecks.FindAsync(id);
            if (null == otc)
            {
                return NotFound();
            }

            otc.Id = id;
            otc.UserLogin = objectToCheck.UserLogin;
            otc.TargetGroupId = objectToCheck.TargetGroupId;
            otc.Name = objectToCheck.Name;
            otc.Description = objectToCheck.Description;
            otc.Location = objectToCheck.Location;
            otc.Type = objectToCheck.Type;
            otc.Model = objectToCheck.Model;
            otc.State = objectToCheck.State;

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        // GET: ObjectToCheck/Delete/5
        public async Task<IActionResult> Delete(uint? id)
        {
            if (id == null || _context.ObjectToChecks == null)
            {
                return NotFound();
            }

            var objectToCheck = await _context.ObjectToChecks
                .Include(o => o.TargetGroup)
                .Include(o => o.UserLoginNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (objectToCheck == null)
            {
                return NotFound();
            }
            return View(objectToCheck);
        }

        // POST: ObjectToCheck/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(uint id)
        {
            if (_context.ObjectToChecks == null)
            {
                return Problem("Entity set 'project_3Context.Objects'  is null.");
            }
            var objectToCheck = await _context.ObjectToChecks.Include(x => x.AuditingLogs).Include(x => x.Inspections).FirstOrDefaultAsync(x => x.Id == id);
            if (objectToCheck != null)
            {
                foreach (var a in objectToCheck.AuditingLogs)
                {
                    foreach (var r in _context.RequirementResults.Where(x => x.AuditingLogsId == a.Id).ToList())
                    {
                        _context.RequirementResults.Remove(r);
                    }
                    _context.AuditingLogs.Remove(a);
                }
                foreach (var i in objectToCheck.Inspections)
                {
                    _context.Inspections.Remove(i);
                }
                _context.ObjectToChecks.Remove(objectToCheck);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ObjectToCheckExists(uint id)
        {
            return (_context.ObjectToChecks?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

MVC/FFMP/FFMP/Controllers/RequirementResultsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FFMP.Data;

namespace FFMP.Controllers
{
    public class RequirementResultsController : Controller
    {
        private readonly project_3Context _context;
        private readonly IHttpContextAccessor _cntxt;

        public RequirementResultsController(project_3Context context, IHttpContextAccessor cntxt)
        {
            _context = context;
            _cntxt = cntxt;
        }

        // GET: RequirementResults
        public async Task<IActionResult> Index()
        {
            if (!UsersController.UserAuthenticated(_cntxt))
                return RedirectToAction("Login", "Users");

            var project_3Context = _context.RequirementResults.Include(r => r.AuditingLogs);
            return View(await project_3Context.ToListAsync());
        }

        // GET: RequirementResults/Details/5
        public async Task<IActionResult> Details(uint? id)
        {
            if (id == null || _context.RequirementResults == null)
            {
                return NotFound();
            }

            var requirementResult = await _context.RequirementResults
                .Include(r => r.AuditingLogs)
                .FirstOrDefaultAsync(m => m.RequirementId == id);
            if (requirementResult == null)
            {
                return NotFound();
            }

            return View(requirementResult);
        }

        // GET: RequirementResults/Create
        public IActionResult Create()
        {
            ViewData["AuditingLogsId"] = new SelectList(_context.AuditingLogs, "Id", "Id");
            return View();
        }

        // POST: RequirementResults/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("RequirementId,AuditingLogsId,Description,Must,Result")] RequirementResult requirementResult)
        {
            _context.Add(requirementResult);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));

            if (ModelState.IsValid)
            {
                _context.Add(requirementResult);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AuditingLogsId"] = new SelectList(_context.AuditingLogs, "Id", "Id", requirementResult.AuditingLogsId);
            return View(requirementResult);
        }

        // GET: RequirementResults/Edit/5
        public async Task<IActionResult> Edit(uint? id)
        {
            if (id == null || _context.RequirementResults == null)
            {
                return NotFound();
            }

            var requirementResult = await _context.RequirementResults.FindAsync(id);
            if (requirementResult == null)
            {
                return NotFound();
            }
            ViewData["AuditingLogsId"] = new SelectList(_context.AuditingLogs, "Id", "Id", requirementResult.AuditingLogsId);
            return View(requirementResult);
        }

        // POST: RequirementResults/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> PostEdit(uint id, [Bind("RequirementId,AuditingLogsId,Description,Must,Result")] RequirementResult requirementResult)
        {
            if (id != requirementResult.RequirementId)
            {
                return NotFound();
            }

            try
            {

                if (requirementResult.Result == null)
                    requirementResult.Result = false;
                _context.Update(requirementResult);

                var rr = _context.RequirementResults.Where(x => x.AuditingLogsId == requirementResult.AuditingLogsId).ToList();
                bool? result = true;
                foreach (var r in rr)
                {
                    if (r.Result == null) { 
                        result = null;
                        break;
                    }
                    if (r.Result == false && r.Must)
                    {
                        result = false;
                    }
                }
                var a = _context.AuditingLogs.First(x => x.Id == requirementResult.AuditingLogsId);                               
                a.Result = result == false ? "NOT OK" : result == true ? "OK" : "INCOMPLETE";

                // Object status is changed if latest auditing
                var la = _context.AuditingLogs.Where(x => x.ObjectId == a.ObjectId).OrderByDescending(x => x.Created).First();
                if (la.Id == a.Id) { 
                    var o = _context.ObjectToChecks.First(x => x.Id == a.ObjectId);
                    o.State = a.Result == "NOT OK" ? false : a.Result == "OK" ? true : o.State;
                }
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!RequirementResultExists(requirementResult.RequirementId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction("Edit", "AuditingLogs", new { id = requirementResult.AuditingLogsId });
        }

        // GET: RequirementResults/Delete/5
        public async Task<IActionResult> Delete(uint? id)
        {
            if (id == null || _context.RequirementResults == null)
            {
                return NotFound();
            }

            var requirementResult = await _context.RequirementResults
                .Include(r => r.AuditingLogs)
                .FirstOrDefaultAsync(m => m.RequirementId == id);
            if (requirementResult == null)
            {
                return NotFound();
            }

            return View(requirementResult);
        }

        // POST: RequirementResults/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(uint id)
        {
            if (_context.RequirementResults == null)
            {
                return Problem("Entity set 'project_3Context.RequirementResults'  is null.");
            }
            var requirementResult = await _context.RequirementResults.FindAsync(id);
            if (requirementResult != null)
            {
                _context.RequirementResults.Remove(requirementResult);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RequirementResultExists(uint id)
        {
            return _context.RequirementResults.Any(e => e.RequirementId == id);
        }
    }
}

MVC/FFMP/FFMP/Views/AuditingLogs/Create.cshtml
@model FFMP.Data.AuditingLog

@{
    ViewData["Title"] = "Create";
}
@section Scripts {
    @{
        await Html.RenderPartialAsync("_Navbar");
    }
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

<h1>Create</h1>

<h4>AuditingLog</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group" style="display:none;">
                <label asp-for="UserLogin" class="control-label"></label>
                <select asp-for="UserLogin" class ="form-control" asp-items="ViewBag.UserLogin"></select>
            </div>
            <div class="form-group" style="display:none;">
                <label asp-for="ObjectId" class="control-label"></label>
                <select asp-for="ObjectId" class ="form-control" asp-items="ViewBag.ObjectId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Created" class="control-label"></label>
                <input asp-for="Created" class="form-control" />
                <span asp-validation-for="Created" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group" style="display:none;">
                <label asp-for="Result" class="control-label"></label>
                <input asp-for="Result" class="form-control" />
                <span asp-validation-for="Result" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<div class="row">
    <h4>Auditing forms requirements</h4>
    <table class="table">
        <thead>
            <tr>
                <th>
                    Description
                </th>
                <th>
                    Mandatory
                </th>
                <th>
                    Result
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.RequirementResults)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Must)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Result)
                    </td>
                </tr>
            }
        </tbody>
    </table>

</div>

<div>
    <input onclick="history.back()" type="button" value="Back" class="btn btn-info" />
</div>

MVC/FFMP/FFMP/Views/AuditingLogs/Delete.cshtml
@model FFMP.Data.AuditingLog

@{
    ViewData["Title"] = "Delete";
}
@section Scripts {
    @{
        await Html.RenderPartialAsync("_Navbar");
    }
    }

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>AuditingLog</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Created)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Created)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Result)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Result)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserLoginNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserLoginNavigation.Login)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Object)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Object.Id)
        </dd>
    </dl>

        <div class="modal fade" id="deleteInsp-@Model.Id" aria-labelledby="DeleteInspLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteInspLabel">Delete inspection</h5>
                    <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>Are you sure you want to delete?</p>
                    <form asp-action="Delete" asp-route-id="@Model.Id" data-id="@Model.Id">
        <input type="hidden" asp-for="Id" />
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Delete</button>
                    </div>
        
    </form>
</div>
        </div>
    </div>
    </div>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <input onclick="history.back()" type="button" value="Back" class="btn btn-info" />   
    </form>
</div>

MVC/FFMP/FFMP/Views/AuditingLogs/Edit.cshtml
@model FFMP.Data.AuditingLog

@{
    ViewData["Title"] = "Edit";
}
@section Scripts {


    @{
        await Html.RenderPartialAsync("_Navbar");
    }
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }
    <script>
        function ok(reqId) {
            console.log("OK");
            $("#Result-" + reqId).val("True");
            $("#Save-" + reqId).click();
            return false;
        }
        function notOk(reqId) {
            debugger
            console.log("Not OK");
            $("#Result-" + reqId).val("False");
            $("#Save-" + reqId).click();
            return false;
        }
    </script>
    <style>
       .ok-True{
            color: #fff;
            background-color: #007bff;
            border-color: #007bff;
        }
         .nok-False{
             color: #fff;
             background-color: #007bff;
             border-color: #007bff;
         }
    </style>

        <h1 class="text-center">@ViewBag.AuditingText</h1>

<hr />


<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group" style="display:none;">
                <label asp-for="UserLogin" class="control-label"></label>
                <select asp-for="UserLogin" class="form-control" asp-items="ViewBag.UserLogin"></select>
                <span asp-validation-for="UserLogin" class="text-danger"></span>
            </div>
            <div class="form-group" style="display:none;">
                <label asp-for="ObjectId" class="control-label"></label>
                <select asp-for="ObjectId" class="form-control" asp-items="ViewBag.ObjectId"></select>
                <span asp-validation-for="ObjectId" class="text-danger"></span>
            </div>
                <div class="form-group" style="display:none;">
                <label asp-for="Created" class="control-label"></label>
                <input asp-for="Created" class="form-control" />
                <span asp-validation-for="Created" class="text-danger"></span>
            </div>
            <div class="form-group" style="display:none;">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group" style="display:none;">
                <label asp-for="Result" class="control-label"></label>
                <input asp-for="Result" class="form-control" />
                <span asp-validation-for="Result" class="text-danger"></span>
            </div>
            <br/>
@*            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" onclick="history.back()"/>
            </div>*@
        </form>
    </div>
</div>
<div class="row">
                <table class="table">
                <thead>
                    <tr>
                        <th>
                            Description
                        </th>
                        <th>
                            Mandatory
                        </th>
                        <th>
                            Result
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.RequirementResults)
                    {
                        <tr>
                            <td>
                        @Html.DisplayFor(modelItem => item.Description)
                            </td>
                            <td>
                        @Html.DisplayFor(modelItem => item.Must)
                            </td>
                            <td>
                                <form asp-action="PostEdit" asp-controller="RequirementResults" asp-route-id="@item.RequirementId">
                                    <input style="display:none;" name='RequirementId' value='@item.RequirementId' />
                                    <input style="display:none;" name='AuditingLogsId' value='@item.AuditingLogsId' />
                                    <input style="display:none;" name='Description' value='@item.Description' />

                            <input style="display:none;" type="checkbox" checked='@item.Must' name='Must' value='@item.Must.ToString().ToLower()' />

                            <input style="display:none;" name='Result' id="Result-@item.RequirementId" value='@item.Result.ToString()' />
                            <button class="btn ok-@item.Result.ToString()" onclick="ok(@item.RequirementId)">Ok</button>
                            <button class="btn nok-@item.Result.ToString()" onclick="notOk(@item.RequirementId)">Not Ok</button>                            
                            <input style="display:none;" id="Save-@item.RequirementId" type="submit" value="Save" class="btn btn-primary" />
                                </form>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
    <div>
        <form asp-action="Index" asp-route-id='@Model.ObjectId'>
            <input type="submit" value="Back" class="btn btn-info" formmethod="get" />
            @*
            <input onclick="history.back()" type="button" value="Back" class="btn btn-info" />  *@
        </form>
    </div>
</div>

MVC/FFMP/FFMP/Views/AuditingLogs/Index.cshtml
@model IEnumerable<FFMP.Data.AuditingLog>

@{
    ViewData["Title"] = "AuditLogs";
}
@section Scripts {
    @{
        await Html.RenderPartialAsync("_Navbar");
    }
    }

    <h1 class="text-center">Auditings @ViewBag.ErrorText</h1>
        
<script>
    $(document).ready(function () {
        
        var table = $('#table').DataTable({
            order: [[0, 'desc']],
        });
    });
</script>
@if (Model.Any() && Model.FirstOrDefault().ObjectId != 0)
{
    <a asp-action="Create" asp-route-id="@Model.FirstOrDefault().ObjectId" class="btn btn-info ">Create auditing</a>
    <br/>
}
else {
    <hr />
    <br />
    <span class="label label-primary mytooltip" title="Go to Service Objects view if you wish to create a new auditing"><img src="~/images/information.png" /></span>

    <br />
    <br />
}
<table class="table table-striped" id="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Created)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Result)
            </th>
            <th>
                Auditor
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Object)
            </th>
            <th>
               Actions
            </th>
        </tr>
    </thead>
    <tbody>
    @foreach (var item in Model) {
            if (item.Created != null)
            {
        <tr>
            <td>
                @item.Created.Value.ToString("yyyy.MM.dd HH.mm.ss")
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Result)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserLoginNavigation.Login)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Object.Name)
            </td>
                    <td>
                        @if (Model.Any() && Model.FirstOrDefault().ObjectId != 0)
                        {
                            <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-info btn-sm">Edit</a>
 }
                        else {
                            <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-info btn-sm">Edit</a>
 
                        }
                        |                       
                    @*<a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger btn-sm">Delete</a>*@
                        <button type="button" class="btn btn-danger btn-sm" data-bs-toggle="modal"
                        data-bs-target="@("#deleteAL-"+item.Id)"
                        data-bs-url="@Url.Action($"Delete/{item.Id}")">
                            Delete
                        </button>
                        @await Html.PartialAsync("_DeletePartialView", item)

            </td>
        </tr>
            }
        }
    </tbody>
</table>
@if (Model.Any() && Model.FirstOrDefault().ObjectId != 0)
{
    <a asp-action="Index" asp-controller="ObjectToCheck" class="btn btn-info ">Back</a>
}