MVC/FFMP/FFMP/Controllers/AuditingFormsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FFMP.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace FFMP.Controllers
{
    public class AuditingFormsController : Controller
    {
        private readonly project_3Context _context;
        private readonly IHttpContextAccessor _ctx;
        public AuditingFormsController(project_3Context context, IHttpContextAccessor ctx)
        {
            _context = context;
            _ctx = ctx;
        }

        // GET: AuditingForms
        public async Task<IActionResult> Index()
        {
            if (!UsersController.UserAuthenticated(_ctx))
                ///!UsersController.UserAuthenticatedAdmin(_ctx)
                return RedirectToAction("Login", "Users");

            var project_3Context = _context.AuditingForms.Include(a => a.TargetGroup).Include(a => a.UserLoginNavigation);
            return View(await project_3Context.ToListAsync());
        }

        // GET: AuditingForms/Details/5
        public async Task<IActionResult> Details(uint? id)
        {
            if (!UsersController.UserAuthenticatedAdmin(_ctx))
                return RedirectToAction("Login", "Users");

            if (id == null || _context.AuditingForms == null)
            {
                return NotFound();
            }

            var auditingForm = await _context.AuditingForms
                .Include(a => a.TargetGroup)
                .Include(a => a.UserLoginNavigation)
                .Include(a => a.Requirements)
                .FirstOrDefaultAsync(m => m.AuditingId == id);
            if (auditingForm == null)
            {
                return NotFound();
            }

            return View(auditingForm);
        }

        // GET: AuditingForms/Create
        public IActionResult Create()
        {
            if (!UsersController.UserAuthenticatedAdmin(_ctx))
                return RedirectToAction("Login", "Users");

            ViewData["TargetGroupId"] = new SelectList(_context.TargetGroups, "Id", "Description");
            ViewData["UserLogin"] = new SelectList(_context.Users, "Login", "Login");
            return View();
        }

        // POST: AuditingForms/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AuditingId,UserLogin,TargetGroupId,Created,Description")] AuditingForm auditingForm)
        {
            auditingForm.Created = DateTime.Now;

            _context.Add(auditingForm);
            await _context.SaveChangesAsync();
            return RedirectToAction("Edit", "AuditingForms", new { id = auditingForm.AuditingId });
        }
        // GET: AuditingForms/Edit/5
        public async Task<IActionResult> Edit(uint? id)
        {
            if (!UsersController.UserAuthenticatedAdmin(_ctx))
                return RedirectToAction("Login", "Users");

            if (id == null || _context.AuditingForms == null)
            {
                return NotFound();
            }

            var auditingForm = await _context.AuditingForms.Include(a => a.Requirements).FirstOrDefaultAsync(x => x.AuditingId == id);
            if (auditingForm == null)
            {
                return NotFound();
            }
            ViewData["TargetGroupId"] = new SelectList(_context.TargetGroups, "Id", "Description", auditingForm.TargetGroupId);
            ViewData["UserLogin"] = new SelectList(_context.Users, "Login", "Login", auditingForm.UserLogin);
            return View(auditingForm);
        }

        // POST: AuditingForms/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(uint id, string actionType, [Bind("AuditingId,UserLogin,TargetGroupId,Created,Description")] AuditingForm auditingForm)
        {
            if (id != auditingForm.AuditingId)
            {
                return NotFound();
            }


            try
            {
                if (actionType != "Save")
                {
                    var req = _context.Requirements.Where(x => x.AuditingAuditingId == auditingForm.AuditingId).ToList();
                    auditingForm.AuditingId = 0;
                    auditingForm.Created = DateTime.Now;
                    auditingForm.Requirements = null;
                    _context.Add(auditingForm);
                    await _context.SaveChangesAsync();

                    foreach (var r in req) {
                        r.AuditingAuditingId = auditingForm.AuditingId;
                        r.ReqId = 0;
                        _context.Requirements.Add(r);
                    }
                    await _context.SaveChangesAsync();
                }
                else { 
                _context.Update(auditingForm);
                await _context.SaveChangesAsync();
                }
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!AuditingFormExists(auditingForm.AuditingId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction("Edit", "AuditingForms", new { id = auditingForm.AuditingId });
        }

        // GET: AuditingForms/Delete/5
        public async Task<IActionResult> Delete(uint? id)
        {
            if (!UsersController.UserAuthenticatedAdmin(_ctx))
                return RedirectToAction("Login", "Users");

            if (id == null || _context.AuditingForms == null)
            {
                return NotFound();
            }

            var auditingForm = await _context.AuditingForms
                .Include(a => a.TargetGroup)
                .Include(a => a.UserLoginNavigation)
                .FirstOrDefaultAsync(m => m.AuditingId == id);
            if (auditingForm == null)
            {
                return NotFound();
            }

            return View(auditingForm);
        }

        // POST: AuditingForms/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(uint id)
        {
            if (_context.AuditingForms == null)
            {
                return Problem("Entity set 'project_3Context.AuditingForms'  is null.");
            }            

            var auditingForm = await _context.AuditingForms.Include(a => a.Requirements).FirstOrDefaultAsync(x => x.AuditingId == id);
            if (auditingForm != null)
            {
                foreach (var r in auditingForm.Requirements)
                {
                    _context.Requirements.Remove(r);
                }
                _context.AuditingForms.Remove(auditingForm);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AuditingFormExists(uint id)
        {
            return _context.AuditingForms.Any(e => e.AuditingId == id);
        }
    }
}

MVC/FFMP/FFMP/Controllers/RequirementsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FFMP.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace FFMP.Controllers
{
    public class RequirementsController : Controller
    {
        private readonly project_3Context _context;
        private readonly IHttpContextAccessor _cntxt;

        public RequirementsController(project_3Context context, IHttpContextAccessor cntxt)
        {
            _context = context;
            _cntxt = cntxt;
        }

        // GET: Requirements
        public async Task<IActionResult> Index()
        {
            if (!UsersController.UserAuthenticated(_cntxt))
                return RedirectToAction("Login", "Users");

            var project_3Context = _context.Requirements.Include(r => r.AuditingAuditing);
            return View(await project_3Context.ToListAsync());
        }

        // GET: Requirements/Details/5
        public async Task<IActionResult> Details(uint? id)
        {
            if (id == null || _context.Requirements == null)
            {
                return NotFound();
            }

            var requirement = await _context.Requirements
                .Include(r => r.AuditingAuditing)
                .FirstOrDefaultAsync(m => m.ReqId == id);
            if (requirement == null)
            {
                return NotFound();
            }

            return View(requirement);
        }

        // GET: Requirements/Create
        public IActionResult Create(uint? AuditingAuditingId)
        {
            var r = new Requirement();
            r.AuditingAuditingId = AuditingAuditingId.Value;
            ViewData["AuditingAuditingId"] = AuditingAuditingId;
            return View(r);
        }

        // POST: Requirements/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ReqId,AuditingAuditingId,Description,Must")] Requirement requirement)
        {
            _context.Add(requirement);
            await _context.SaveChangesAsync();
            return RedirectToAction("Edit", "AuditingForms", new { id = requirement.AuditingAuditingId });

            if (ModelState.IsValid)
            {
                _context.Add(requirement);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            else
            {
                var errors = ModelState.Select(x => x.Value.Errors)
                       .Where(y => y.Count > 0)
                       .ToList();
            }
            ViewData["AuditingAuditingId"] = new SelectList(_context.AuditingForms, "AuditingId", "AuditingId", requirement.AuditingAuditingId);
            return RedirectToAction("Edit", "AuditingForms", new { id = requirement.AuditingAuditingId });
        }

        // GET: Requirements/Edit/5
        public async Task<IActionResult> Edit(uint? id)
        {
            if (id == null || _context.Requirements == null)
            {
                return NotFound();
            }

            var requirement = await _context.Requirements.FindAsync(id);
            if (requirement == null)
            {
                return NotFound();
            }
            ViewData["AuditingAuditingId"] = new SelectList(_context.AuditingForms, "AuditingId", "AuditingId", requirement.AuditingAuditingId);
            return View(requirement);
        }

        // POST: Requirements/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(uint id, [Bind("ReqId,AuditingAuditingId,Description,Must")] Requirement requirement)
        {
            if (id != requirement.ReqId)
            {
                return NotFound();
            }

            try
            {
                _context.Update(requirement);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!RequirementExists(requirement.ReqId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction("Edit", "AuditingForms", new { id = requirement.AuditingAuditingId });
        }

        // GET: Requirements/Delete/5
        public async Task<IActionResult> Delete(uint? id)
        {
            if (id == null || _context.Requirements == null)
            {
                return NotFound();
            }

            var requirement = await _context.Requirements
                .Include(r => r.AuditingAuditing)
                .FirstOrDefaultAsync(m => m.ReqId == id);
            if (requirement == null)
            {
                return NotFound();
            }

            return View(requirement);
        }

        // POST: Requirements/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(uint id)
        {
            if (_context.Requirements == null)
            {
                return Problem("Entity set 'project_3Context.Requirements'  is null.");
            }
            var requirement = await _context.Requirements.FindAsync(id);
            if (requirement != null)
            {
                _context.Requirements.Remove(requirement);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction("Edit", "AuditingForms", new { id = requirement.AuditingAuditingId });
        }

        private bool RequirementExists(uint id)
        {
            return _context.Requirements.Any(e => e.ReqId == id);
        }
    }
}

MVC/FFMP/FFMP/Views/AuditingForms/Create.cshtml
@model FFMP.Data.AuditingForm

@{
    ViewData["Title"] = "Create";
}
@section Scripts {
    @{
        await Html.RenderPartialAsync("_Navbar");
    }
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }
<h1>Create</h1>

<h4>Auditing form</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group" style="display:none;">
                <label asp-for="UserLogin" class="control-label"></label>
                <select asp-for="UserLogin" class ="form-control" asp-items="ViewBag.UserLogin"></select>
            </div>
            <div class="form-group">
                    <label class="control-label">Target group</label>
                    <select asp-for="TargetGroupId" class="form-control" asp-items="ViewBag.TargetGroupId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <br/>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
    <br />
<div>
        <input onclick="history.back()" type="button" value="Back" class="btn btn-info" />
</div>

MVC/FFMP/FFMP/Views/AuditingForms/Delete.cshtml
@model FFMP.Data.AuditingForm

@{
    ViewData["Title"] = "Delete";
}
@section Scripts {
    @{
        await Html.RenderPartialAsync("_Navbar");
    }
    }

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>AuditingForm</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Created)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Created)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserLoginNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserLoginNavigation.Login)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TargetGroup)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TargetGroup.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="AuditingId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <input onclick="history.back()" type="button" value="Back" class="btn btn-info" />
    </form>
</div>

MVC/FFMP/FFMP/Views/AuditingForms/Details.cshtml
@model FFMP.Data.AuditingForm

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>AuditingForm</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Created)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Created)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserLoginNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserLoginNavigation.Login)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TargetGroup)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TargetGroup.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.AuditingId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MVC/FFMP/FFMP/Views/AuditingForms/Edit.cshtml
@model FFMP.Data.AuditingForm

@{
    ViewData["Title"] = "Edit";
}
@section Scripts {
    @{await Html.RenderPartialAsync("_Navbar");}
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

<h1>Edit</h1>

<h4>Auditing form</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="AuditingId" />
            <div class="form-group" style="display:none;">
                <label asp-for="UserLogin" class="control-label"></label>
                <select asp-for="UserLogin" class="form-control" asp-items="ViewBag.UserLogin"></select>
                <span asp-validation-for="UserLogin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Target group</label>
                <select asp-for="TargetGroupId" class="form-control" asp-items="ViewBag.TargetGroupId"></select>
                <span asp-validation-for="TargetGroupId" class="text-danger"></span>
            </div>
            <div class="form-group" style="display:none;">
                <label asp-for="Created" class="control-label"></label>
                <input asp-for="Created" class="form-control" />
                <span asp-validation-for="Created" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
                <br />
            <div class="form-group">
                    <input type="submit" value="Save" name="actionType" class="btn btn-primary" />
                    <input type="submit" value="Save as new" name="actionType" class="btn btn-info" />
            </div>
        </form>
    </div>
</div>
    <br />
    <br />
<div class="row">
        
    <h4>Auditing requirements</h4><br />
    <p>
        <a asp-controller="Requirements" asp-action="Create" asp-route-AuditingAuditingId="@Model.AuditingId" class="btn btn-info">Add requirement</a>


    </p>
    <table class="table">
        <thead>
            <tr>
                <th>
                    Description
                </th>
                <th>
                    Mandatory
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Requirements)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Must)
                    </td>
                    <td>
                        <a asp-controller="Requirements" asp-action="Edit" asp-route-id="@item.ReqId" class="btn btn-info">Edit</a> |
                        <a asp-controller="Requirements" asp-action="Delete" asp-route-id="@item.ReqId" class="btn btn-danger">Delete</a>


                        @*<button type="button" class="btn btn-info" data-bs-toggle="modal" data-bs-target="@("#deleteInsp-"+item.Id)" data-bs-url="@Url.Action($"Delete/{item.Id}")">Delete</button>
                        @await Html.PartialAsync("_DeletePartialView", item)*@

                    </td>
                </tr>
            }
        </tbody>
    </table>

</div>

<div>
    <a asp-action="index" class="btn btn-info" formmethod="get">Back</a>
</div>

MVC/FFMP/FFMP/Views/AuditingForms/Index.cshtml
@model IEnumerable<FFMP.Data.AuditingForm>

@{
    ViewData["Title"] = "AuditForms";
}

@section Scripts {
    @{
        await Html.RenderPartialAsync("_Navbar");
    }
    }

    <h1 class="text-center">Auditing Forms</h1>
    <hr />
    <br />

    <form asp-action="Create">
        <input type="submit" value="Create Form" class="btn btn-info" formmethod="get" />
    </form>
    <br />
    <script>
        $(document).ready(function () {

            var table = $('#table').DataTable({
                order: [[0, 'desc']],
            });
        });
    </script>
    <table class="table table-striped" id="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Created)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                Creator
            </th>
            <th>
                Target group
            </th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @item.Created.ToString("yyyy.MM.dd HH.mm.ss")
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserLoginNavigation.Login)
            </td>
            <td>
                    @Html.DisplayFor(modelItem => item.TargetGroup.Description)
            </td>
            <td>
                    <a asp-action="Edit" asp-route-id="@item.AuditingId" class="btn btn-info btn-sm">Edit</a> |
                    @*<a asp-action="Delete" asp-route-id="@item.AuditingId" class="btn btn-danger btn-sm">Delete</a>*@
                    <button type="button" class="btn btn-danger btn-sm" data-bs-toggle="modal"
                        data-bs-target="@("#deleteAF-"+item.AuditingId)"
                        data-bs-url="@Url.Action($"Delete/{item.AuditingId}")">
                        Delete
                    </button>
                    @await Html.PartialAsync("_DeletePartialView", item)

            </td>
        </tr>
}
    </tbody>
</table>

MVC/FFMP/FFMP/Views/AuditingForms/_DeletePartialView.cshtml
@model FFMP.Data.AuditingForm

@{
    ViewData["Title"] = "Delete";
}
<div class="modal fade" id="deleteAF-@Model.AuditingId" aria-labelledby="DeleteAFLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteAFLabel">Delete Form</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete?</p>
                <form asp-action="Delete" asp-route-id="@Model.AuditingId" data-id="@Model.AuditingId">
                    <input type="hidden" asp-for="AuditingId" />
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Delete</button>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>